### ISSUE TITLE
Disable in runtime

### ISSUE THREAD

**Issue by FredyC** [spredfast/react-transform-render-visualizer#8]
Kinda related to #3, but it's not very practical to have to modify the code to disable this. I would like to see some option to disable in runtime so it doesn't obstruct view when trying to style the component. Could be even something simple like "ctrl + click".

Perhaps it would be even helpful to have ability do disable this globally, for example with some value in localStorage or within url.

**Comment by trobertsonsf** [comment]
In our apps we have a local storage wrapper that determines if we should
show the visualizer or not and it works well, but don't think we would want
to tie the library itself to LS. Ctrl-click or something is interesting.

On Saturday, March 12, 2016, Daniel K. <notifications@github.com> wrote:

> Kinda related to #3
> <https://github.com/spredfast/react-transform-render-visualizer/issues/3>,
> but it's not very practical to have to modify the code to disable this. I
> would like to see some option to disable in runtime so it doesn't obstruct
> view when trying to style the component. Could be even something simple
> like "ctrl + click".
>
> Perhaps it would be even helpful to have ability do disable this globally,
> for example with some with in localStorage or within url.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spredfast/react-transform-render-visualizer/issues/8>.
>


-- 
--

*Tim Robertson*
UI Arch Conversations, Spredfast Inc.
E :: trobertson@spredfast.com    T :: @rtimothy
<https://twitter.com/rtimothy>
Spredfast Inc.'s Twitter <https://twitter.com/Spredfast> | Facebook
<http://www.facebook.com/Spredfast> | Blog <http://www.spredfast.com/blog/>

**Comment by FredyC** [comment]
@trobertsonsf So you have a wrapper for every component that checks value in LS and sets the static property `rerenderViz` based on it? That's sounds awfully silly. How hard is to actually implement global off switch? It could be even something simple like `require('react-transform-render-visualizer').disable()` so it would keep its own internal state if wrapper should be visible. Then this can be easily controlled by some light custom code.

**Comment by trobertsonsf** [comment]
@FredyC We have a small utility that that checks that flag in localstorage and caches the value, when our components use it, something like this...

`static rerenderViz = isRenderVisualizerEnabled();`

**Comment by FredyC** [comment]
Sorry, but I still think this is rather silly solution in general. You have to pollute the production code with something for debugging. Never seen that as a good thing to do. Why I am suggesting would be much more robust and easier without everyone creating their own "toggler".
